### ISSUE TITLE
DateUtil.getDateFromUTCString is not thread safe

### ISSUE THREAD

**Issue by steelbytes** [kinecosystem/kin-devplatform-android#26]
DateUtil.getDateFromUTCString uses SimpleDateFormat which is not thread safe.

simple fix is to use ThreadLocal<SimpleDateFormat> for your date formatters

**Comment by dillontking** [comment]
@yosriz @drEfrati

**Comment by drEfrati** [comment]
You are generally right but in our case we use it internally always with only one thread.
Anyway we can wrap it with ThreadLocal<SimpleDateFormat>  in future fix.

Thanks.

**Comment by yosriz** [comment]
fixed by
https://github.com/kinecosystem/kin-devplatform-android/pull/41
