### ISSUE TITLE
Production environment returning testnet JWTS

### ISSUE THREAD

**Issue by mea-licensing** [kinecosystem/kin-devplatform-android#66]
**Environment:**
kin-devplatform-sdk:1.3.0
kin-migration-module-android:1.0.8
kin-ecosystem-android-sdk:recovery:d73ef56

**Steps to reproduce:**

1. SDK started with  `Environment.getProduction()`

2. User initiates a purchase

3. Fetch `spendJwt` from server

4. Call `Kin.purchase(spendJwt)`

5. In `KinCallback<OrderConfirmation>`, `onResponse(OrderConfirmation response)` is called

6. response.getJwtConfirmation() returns a JWT that has the following in the payment object:
```
"payment": {
    "blockchain": "stellar-testnet",
    "transaction_id": "ae2a1307a8f5a8d8840168309bba7a039f82bf0b853a8638e3f314394206e974"
  },
```

7. The JWT from response.getJwtConfirmation() is sent to server for confirmation, which fails because the header `kid` can't be matched against production certs.

Is there something misconfigured on my end or something I'm not seeing?

**Comment by cohenalex** [comment]
@mea-licensing we have reached you directly via the Kin support platform ticket.
