### ISSUE TITLE
feature request:  enable android/ios apps to tell if there is a pre-existing wallet on the device (for this app/device)

### ISSUE THREAD

**Issue by rorymc** [kinecosystem/kin-devplatform-android#67]
We would like to avoid the issue where, for some reason / bug, the wrong UUID is being passed to Kin.start().

This could happen for a variety of bugs/caching issues/reasons, one of which is Firebase SDK bugs.

When those bugs arise, then app ends up incorrectly erasing the user's wallet.

This is unfortunately unrecoverable on iOS, because there is no backup/restore on kin-devplatform-ios (we realize with Kin3 SDK, backup/restore is present for both android/ios).

hence, this feature request applies to kin-sdk-{android,ios} as well, as we may want to detect before running through overwriting existing wallet/creating a new wallet.

**Comment by cohenalex** [comment]
Hi Rory,
We don't plan to develop features for the dev platform SDKs.
The feature you are requesting exists in the Kin-sdk; using the getAccountCount method you can check how many accounts exist on the device. The Kin SDK allows you to manage multiple accounts.

**Comment by rorymc** [comment]
Wonderful, thank you for confirming this is possible in the new kin-sdk-{ios,android}, Alex !

my main desire was to avoid cases where, due to our own app bug, we accidentally erase the wallet of the user.

(difficult situation on ios devplatform SDK, because there is no backup)
